### ISSUE TITLE
Firefox Nightly support?

### ISSUE THREAD

**Issue by SheepKid12** [kustodian/extended-statusbar#49]
Will there be support for firefox nightly/future versions of firefox?

**Comment by kustodian** [comment]
I don't have time to work on it and as far as I can see @adoxa is in the same spot. Of course if someone is willing to do the work and submit a PR we'll try to review, test and deploy it.

**Comment by adoxa** [comment]
I'm still using the unbranded 51 version (54 didn't have the developer tools and 55 had other issues, such as missing the back/forward & history buttons [possibly a Classic Theme Restorer issue] and not updating the Work Offline icon). I don't know if I'll continue with Firefox or switch to Pale Moon or Waterfox.

**Comment by adoxa** [comment]
I doubt I will - it looks like a lot of the extensions I use will break, so I'll probably be sticking with unbranded 55 for a while (turns out it was Work Offline causing all the issues, so now I'm using Offline Switch). Most people seem to suggest using 52ESR, as that will keep getting security updates till June 2018, then figure out what to do. [Basilisk](http://basilisk-browser.org/) might be worth keeping an eye on, or [Vivaldi](https://vivaldi.com/) for something different.
